/* CADASTRO CURRICULO
-> Nome
-> CPF
-> RG
-> Endereco
-> Email
-> Nivel Escolaridade
-> Especializacoes
-> Lista de ultimos empregos
-> Motivo para demissao da ultima empresa
-> Como descobriu o cadastro de curriculum
Caso seja feminino, se tem filhos e se deseja ter filhos
*/
START TRANSACTION;
delimiter $$

CREATE DATABASE `sistemacurriculo` /*!40100 DEFAULT CHARACTER SET latin1 */$$

SET FOREIGN_KEY_CHECKS=0;

CREATE TABLE CURRICULO (
	ID_CURRICULO 				INT NOT NULL AUTO_INCREMENT,
	NM_NOME 					VARCHAR(100),
	I_CPF 					    INT,
	I_RG      					INT,
	NM_LOGRADOURO 				VARCHAR(100),
	NM_EMAIL      				VARCHAR(100),
	ID_NIVEL_ESCOLARIDADE       INT,
	ID_EMPREGO_ATUAL            INT,
	NM_COMO_NOS_ACHOU           VARCHAR(200),
    IS_TEM_FILHOS               BIT,
	I_QTD_FILHOS                INT,
    IS_QUER_TER_FILHOS          BIT,
	PRIMARY KEY PK_CURRI_ID_CURR (ID_CURRICULO),
	INDEX (ID_NIVEL_ESCOLARIDADE),
	INDEX (ID_EMPREGO_ATUAL),
	FOREIGN KEY FK_CURR_ID_NIV_ESCO (ID_NIVEL_ESCOLARIDADE) REFERENCES ESCOLARIDADE (ID_ESCOLARIDADE),
	FOREIGN KEY FK_CURR_ID_EMP_ATU  (ID_EMPREGO_ATUAL)      REFERENCES EMPREGO (ID_EMPREGO)
);

CREATE TABLE ESPECIALIZACAO (
	ID_ESPECIALIZACAO INT  NOT NULL AUTO_INCREMENT,
	ID_CURRICULO      INT,
	NM_CURSO VARCHAR(100),
	NM_INSTITUICAO VARCHAR(100),
	DT_INICIO DATE,
	DT_FIM    DATE,
	PRIMARY KEY PK_ESPE_ID_ESP_ID_CUR (ID_ESPECIALIZACAO, ID_CURRICULO),
	FOREIGN KEY FK_ESPE_ID_CUR        (ID_CURRICULO)      REFERENCES CURRICULO (ID_CURRICULO)
);

CREATE TABLE EMPREGO (
	ID_EMPREGO INT  NOT NULL AUTO_INCREMENT,
	ID_CURRICULO INT,
	NM_EMPRESA VARCHAR(50),
	NM_DESCRICAO VARCHAR(500),
	DT_ENTRADA   DATE,
	DT_SAIDA     DATE,
	NM_MOTIVO_DEMISSAO VARCHAR(200),
	PRIMARY KEY PK_EMPR_ID_EMP (ID_EMPREGO, ID_CURRICULO),
	FOREIGN KEY FK_EMPR_ID_CURR (ID_CURRICULO)      REFERENCES CURRICULO (ID_CURRICULO)
);

CREATE TABLE ESCOLARIDADE (
	ID_ESCOLARIDADE INT  NOT NULL AUTO_INCREMENT,
	NM_NOME VARCHAR(100),
	PRIMARY KEY PK_ESCO_ID_ESC (ID_ESCOLARIDADE)
);

SET FOREIGN_KEY_CHECKS=1;
COMMIT;