use sistemacurriculo;

/*
Cadastro Empresas
Nome
CNPJ
Numero de vagas disponiveis
*/
/*
Cadastro Vaga
Nome do cargo
Descrição do cargo
Requisito minimo (deve ter no cadastro do candidato)
Nível de linguam inglesa
Escolaridade
Experiencia
Tempo
*/
/*
CADASTRO USUARIO
LOGIN
SENHA
*/
START TRANSACTION;

SET FOREIGN_KEY_CHECKS=0;

CREATE TABLE USUARIO (
	ID_USUARIO INT,
	NM_SENHA   VARCHAR(20),
	PRIMARY KEY PK_USUA_ID_USU (ID_USUARIO)
);

CREATE TABLE EMPRESA (
	ID_EMPRESA 		 INT,
	NM_EMPRESA 		 VARCHAR(100),
	I_CNPJ     		 INT,
	PRIMARY KEY PK_EMPR_ID_EMP (ID_EMPRESA)
);

CREATE TABLE VAGA (
	ID_VAGA               INT,
	NM_NOME_CARGO         VARCHAR(100),
	NM_DESC_CARGO         VARCHAR(200),
	ID_ESCOLARIDADE       INT,
	I_TEMPO_EXPERIENCIA   INT,
	I_QTD_VAGAS_DISP      INT,
	PRIMARY KEY PK_VAGA_ID_VAG (ID_VAGA),
	FOREIGN KEY FK_VAGA_ID_ESC (ID_ESCOLARIDADE) REFERENCES ESCOLARIDADE (ID_ESCOLARIDADE)
);

CREATE TABLE IDIOMA (
	ID_IDIOMA      INT,
	NM_NOME_IDIOMA VARCHAR(100),
	PRIMARY KEY PK_IDIO_ID_IDI (ID_IDIOMA)
);

CREATE TABLE NIVEL_IDIOMA_CURRICULO (
	ID_IDIOMA       INT,
	ID_CURRICULO    INT,
	ID_NIVEL_IDIOMA INT,
	PRIMARY KEY PK_IDIO_CURRI_ID_IDI_CUR_NIV_IDI (ID_IDIOMA, ID_CURRICULO, ID_NIVEL_IDIOMA),
	FOREIGN KEY FK_IDIO_ID_IDI          (ID_IDIOMA)       REFERENCES IDIOMA       (ID_IDIOMA),
	FOREIGN KEY FK_CURR_ID_CUR          (ID_CURRICULO)    REFERENCES CURRICULO    (ID_CURRICULO),
	FOREIGN KEY FK_NIVE_IDIO_ID_NIV_IDI (ID_NIVEL_IDIOMA) REFERENCES NIVEL_IDIOMA (ID_NIVEL_IDIOMA)
);

CREATE TABLE NIVEL_IDIOMA (
	ID_NIVEL_IDIOMA INT,
	NM_NIVEL        VARCHAR(100),
	PRIMARY KEY PK_NIVE_IDIO_ID_NIV_IDI (ID_NIVEL_IDIOMA)
);

SET FOREIGN_KEY_CHECKS=1;

COMMIT;