USE SISTEMACURRICULO;

INSERT INTO USUARIO      (NM_SENHA, NM_LOGIN)  VALUES ('123', 'FEAN');
INSERT INTO EMPRESA      (NM_EMPRESA, S_CNPJ) VALUES ('INTELBRAS', '52135918000141');
INSERT INTO IDIOMA       (NM_NOME_IDIOMA)      VALUES ('INGLES');
INSERT INTO NIVEL_IDIOMA (NM_NIVEL)            VALUES ('BASICO');
INSERT INTO NIVEL_IDIOMA (NM_NIVEL)            VALUES ('INTERMEDIARIO');
INSERT INTO NIVEL_IDIOMA (NM_NIVEL)            VALUES ('AVANÇADO');
INSERT INTO NIVEL_IDIOMA (NM_NIVEL)            VALUES ('FLUENTE');
INSERT INTO ESCOLARIDADE (NM_NOME)     VALUES ('ENSINO FUNDAMENTAL INCOMPLETO');
INSERT INTO ESCOLARIDADE (NM_NOME)     VALUES ('ENSINO FUNDAMENTAL COMPLETO');
INSERT INTO ESCOLARIDADE (NM_NOME)     VALUES ('ENSINO MÉDIO INCOMPLETO');
INSERT INTO ESCOLARIDADE (NM_NOME)     VALUES ('ENSINO MÉDIO COMPLETO');
INSERT INTO ESCOLARIDADE (NM_NOME)     VALUES ('ENSINO SUPERIOR INCOMPLETO');
INSERT INTO ESCOLARIDADE (NM_NOME)     VALUES ('ENSINO SUPERIOR COMPLETO');
INSERT INTO CURRICULO (NM_NOME, S_CPF, S_RG, NM_LOGRADOURO, NM_EMAIL, ID_NIVEL_ESCOLARIDADE, ID_EMPREGO_ATUAL, NM_COMO_NOS_ACHOU, IS_TEM_FILHOS, I_QTD_FILHOS, IS_QUER_TER_FILHOS)
VALUES ('GABRIEL', '65334545', '7898778', 'RUA PRAÇA XV', 'EMAIL@EMAIL.COM.BR', 2, NULL, 'GOOGLE', 0, 0, 0);
INSERT INTO CURRICULO (NM_NOME, S_CPF, S_RG, NM_LOGRADOURO, NM_EMAIL, ID_NIVEL_ESCOLARIDADE, ID_EMPREGO_ATUAL, NM_COMO_NOS_ACHOU, IS_TEM_FILHOS, I_QTD_FILHOS, IS_QUER_TER_FILHOS)
VALUES ('RAFAEL', '23423466', '678678', 'RUA HERCILIO LUZ', 'EMAIL@EMAIL.COM.BR', 2, NULL, 'GOOGLE', 0, 0, 0);
INSERT INTO CURRICULO (NM_NOME, S_CPF, S_RG, NM_LOGRADOURO, NM_EMAIL, ID_NIVEL_ESCOLARIDADE, ID_EMPREGO_ATUAL, NM_COMO_NOS_ACHOU, IS_TEM_FILHOS, I_QTD_FILHOS, IS_QUER_TER_FILHOS)
VALUES ('JOAO', '867867878', '45646564', 'RUA BEIRA MAR', 'EMAIL@EMAIL.COM.BR', 2, NULL, 'GOOGLE', 0, 0, 0);
INSERT INTO CURRICULO (NM_NOME, S_CPF, S_RG, NM_LOGRADOURO, NM_EMAIL, ID_NIVEL_ESCOLARIDADE, ID_EMPREGO_ATUAL, NM_COMO_NOS_ACHOU, IS_TEM_FILHOS, I_QTD_FILHOS, IS_QUER_TER_FILHOS)
VALUES ('MAURICIO', '34545787', '567533', 'RUA PRESIDENTE CRUZ', 'EMAIL@EMAIL.COM.BR', 2, NULL, 'GOOGLE', 0, 0, 0);
INSERT INTO EMPREGO ( 	ID_CURRICULO, NM_EMPRESA, NM_CARGO, NM_DESCRICAO, DT_ENTRADA, DT_SAIDA, NM_MOTIVO_DEMISSAO) 
VALUES (1, 'NESTLE', 'Vendedor', 'TRABALHEI COMO VENDEDOR', '2012/01/01', '2012/05/15', 'ROUBEI UM NESCAU' );
INSERT INTO EMPREGO ( 	ID_CURRICULO, NM_EMPRESA, NM_CARGO, NM_DESCRICAO, DT_ENTRADA, DT_SAIDA, NM_MOTIVO_DEMISSAO) 
VALUES (2, 'DISTLE', 'Consultor Comercial', 'TRABALHEI COMO CONSULTOR COMERCIAL', '2011/03/05', '2012/08/15', 'ROUBEI UM KINDER OVO' );
INSERT INTO EMPREGO ( 	ID_CURRICULO, NM_EMPRESA, NM_CARGO, NM_DESCRICAO, DT_ENTRADA, DT_SAIDA, NM_MOTIVO_DEMISSAO) 
VALUES (3, 'COCA COLA', 'Produção','TRABALHEI NA AREA DE PRODUÇÃO', '2010/04/09', '2012/01/11', 'ROUBEI UMA COCA' );
INSERT INTO EMPREGO ( 	ID_CURRICULO, NM_EMPRESA, NM_CARGO, NM_DESCRICAO, DT_ENTRADA, DT_SAIDA, NM_MOTIVO_DEMISSAO) 
VALUES (4, 'TECNOLOGIA INFORMATICA', 'HelpDesk','TRABALHEI COMO HELPDESK', '2015/01/02', '2015/03/16', 'BRIGUEI COM MEU CHEFE' );
INSERT INTO ESPECIALIZACAO ( ID_CURRICULO, NM_CURSO, NM_INSTITUICAO, DT_INICIO, DT_FIM)
VALUES (1, 'CURSO SUPERIOR EM SISTEMAS DA INFORMAÇÃO', 'FACULDADE ENERGIA', '2013/01/01','2017/01/01');
INSERT INTO ESPECIALIZACAO ( ID_CURRICULO, NM_CURSO, NM_INSTITUICAO, DT_INICIO, DT_FIM)
VALUES (2, 'DESIGNER', 'UFSC', '2012/06/01','2016/01/01');
INSERT INTO ESPECIALIZACAO ( ID_CURRICULO, NM_CURSO, NM_INSTITUICAO, DT_INICIO, DT_FIM)
VALUES (3, 'CIÊNCIAS DA COMPUTAÇÃO', 'UNIVALI', '2010/01/01','2015/01/01');
INSERT INTO ESPECIALIZACAO ( ID_CURRICULO, NM_CURSO, NM_INSTITUICAO, DT_INICIO, DT_FIM)
VALUES (4, 'MECANICA', 'UDESC', '2008/06/01','2013/01/01');
INSERT INTO NIVEL_IDIOMA_CURRICULO (ID_IDIOMA, ID_CURRICULO, ID_NIVEL_IDIOMA)
VALUES (1, 1,1);
INSERT INTO NIVEL_IDIOMA_CURRICULO (ID_IDIOMA, ID_CURRICULO, ID_NIVEL_IDIOMA)
VALUES (1, 2,2);
INSERT INTO NIVEL_IDIOMA_CURRICULO (ID_IDIOMA, ID_CURRICULO, ID_NIVEL_IDIOMA)
VALUES (1, 3,3);
INSERT INTO NIVEL_IDIOMA_CURRICULO (ID_IDIOMA, ID_CURRICULO, ID_NIVEL_IDIOMA)
VALUES (1, 4,4);
INSERT INTO VAGA ( NM_NOME_CARGO, NM_DESC_CARGO, ID_ESCOLARIDADE, I_TEMPO_EXPERIENCIA, I_QTD_VAGAS_DISP, ID_EMPRESA)
VALUES ('CONSULTOR COMERCIAL', 'VENDER PRODUTOS', 1, 2, 5, 1);

COMMIT;