USE SISTEMACURRICULO;

SELECT C.ID_CURRICULO, C.NM_NOME AS NOME_CANDIDATO, E.NM_NOME AS ESCOLARIDADE, C.S_CPF AS CPF, C.S_RG AS RG,
C.NM_LOGRADOURO AS RUA, C.NM_EMAIL AS EMAIL, C.NM_COMO_NOS_ACHOU AS COMO_NOS_ACHOU, C.IS_TEM_FILHOS AS TEM_FILHOS,
C.I_QTD_FILHOS AS _QTD_FILHOS, C.IS_QUER_TER_FILHOS AS QUER_TER_FILHOS,
C.ID_EMPREGO_ATUAL AS EMPREGADO 
FROM CURRICULO C
JOIN ESCOLARIDADE E  ON C.ID_NIVEL_ESCOLARIDADE = E.ID_ESCOLARIDADE
LEFT JOIN EMPREGO EA ON C.ID_EMPREGO_ATUAL = EA.ID_EMPREGO 
JOIN EMPREGO EM ON C.ID_CURRICULO = EM.ID_CURRICULO 
WHERE E.ID_ESCOLARIDADE = 2
AND   UPPER(EM.NM_CARGO) LIKE UPPER('%VENDEDOR%');